### ISSUE TITLE
On the fresh run with cifar10 on macos 11.5.2

### ISSUE THREAD

**Issue by stoneyang** [learning-at-home/hivemind#498]
Hi, there,

Can't wait to use this awesome tool! 

But when first running the cifar10 example on my mac, the following error received: 
```
Files already downloaded and verified
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    dht = hivemind.DHT(start=True)
  File "/Users/Code/hivemind/hivemind/dht/dht.py", line 88, in __init__
    self.run_in_background(await_ready=await_ready)
  File "/Users/Code/hivemind/hivemind/dht/dht.py", line 148, in run_in_background
    self.wait_until_ready(timeout)
  File "/Users/Code/hivemind/hivemind/dht/dht.py", line 151, in wait_until_ready
    self._ready.result(timeout=timeout)
  File "/Users/Code/hivemind/hivemind/utils/mpfuture.py", line 257, in result
    return super().result(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
hivemind.p2p.p2p_daemon_bindings.control.P2PDaemonError: Daemon failed to start: /Users/Code/hivemind/hivemind/hivemind_cli/p2pd: /Users/Code/hivemind/hivemind/hivemind_cli/p2pd: cannot execute binary file
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by borzunov** [comment]
Hi @stoneyang!

I'm afraid we don't have the proper macOS support yet. Could you please try using Docker (as recommended in the ["System requirements"](https://github.com/learning-at-home/hivemind#system-requirements)) or a Linux machine?

Don't hesitate to contact us if you run into any issues.

**Comment by stoneyang** [comment]
> Hi @stoneyang!
> 
> I'm afraid we don't have the proper macOS support yet. Could you please try using Docker (as recommended in the ["System requirements"](https://github.com/learning-at-home/hivemind/blob/master/README.md#system-requirements)) or a Linux machine?
> 
> Don't hesitate to contact us if you run into any issues :)

Successfully run by pulling master image to mac, thanks!
