### ISSUE TITLE
Failed to close hivemind.P2P

### ISSUE THREAD

**Issue by borzunov** [learning-at-home/hivemind#564]
```python
Reachability service failed: FileNotFoundError(2, 'No such file or directory')
Exception ignored in: <function P2P.__del__ at 0x7fbec8be5f70>
Traceback (most recent call last):
  File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/p2p/p2p_daemon.py", line 636, in __del__
    self._terminate()
  File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/p2p/p2p_daemon.py", line 657, in _terminate
    self._child.terminate()
  File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/asyncio/subprocess.py", line 141, in terminate
    self._transport.terminate()
  File "uvloop/handles/process.pyx", line 636, in uvloop.loop.UVProcessTransport.terminate
  File "uvloop/handles/process.pyx", line 378, in uvloop.loop.UVProcessTransport._check_proc
ProcessLookupError:
Exception ignored in: <function Client.__del__ at 0x7fbec8bd7a60>
Traceback (most recent call last):
  File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/p2p/p2p_daemon_bindings/p2pclient.py", line 53, in __del__
    self.close()
  File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/p2p/p2p_daemon_bindings/p2pclient.py", line 50, in close
    self.control.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by borzunov** [comment]
Fixed in #565.
