### ISSUE TITLE
[BUG] hivemind.compression is not compatible with bitsandbytes == 0.39.1

### ISSUE THREAD

**Issue by borzunov** [learning-at-home/hivemind#572]
With bitsandbytes == 0.39.1 (the first version with 4-bit support), we get this for `CompressionType.BLOCKWISE_8BIT`:

```python
Traceback (most recent call last):
  File "/storage/hdd1/jheuristic/exp/decentralized/borzunov/petals/src/petals/server/handler.py", line 289, in rpc_backward
    return runtime_pb2.ExpertResponse(tensors=self._serialize_grads(grads, requested_backends, metadata))
  File "/storage/hdd1/jheuristic/exp/decentralized/borzunov/petals/src/petals/server/handler.py", line 338, in _serialize_grads
    return [
  File "/storage/hdd1/jheuristic/exp/decentralized/borzunov/petals/src/petals/server/handler.py", line 339, in <listcomp>
    serialize_torch_tensor(result.to(proto.dtype), compression, allow_inplace=True)
  File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/compression/serialization.py", line 41, in serialize_torch_tensor
    return compression.compress(tensor, info, allow_inplace)
  File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/compression/quantization.py", line 147, in compress
    quantized, (absmax, codebook) = self.quantize(tensor, allow_inplace=allow_inplace)
  File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/compression/quantization.py", line 138, in quantize
    quantized, (absmax, codebook) = quantize_blockwise(tensor)
ValueError: too many values to unpack (expected 2)
```

That is because bnb 0.39.1 returns more params in `quantize_blockwise()` and requires more params in `dequantize_blockwise()` (4 params and 2 `None`s instead of just `(absmax, codebook)`): [code](https://github.com/TimDettmers/bitsandbytes/blame/4395d68cf6beda911c1c3e5633debf15652e2902/bitsandbytes/functional.py#L634)

Discovered in https://github.com/bigscience-workshop/petals/pull/333.

**Comment by hrishikeshio** [comment]
can we use 0.38 till the fix? I tried and I am getting these kind of errors. 
Jul 19 22:14:44.627 [WARN] [hivemind.averaging.partition.finalize:173] Averaging: received 48.1% results
Jul 19 22:14:16.398 [WARN] [hivemind.averaging.partition.finalize:270] Reducer: received 50.0% of input tensors

**Comment by justheuristic** [comment]
Thank you! i'll try 0.38 and newer versions (e.g. 0.40.post*) and check for similar errors

**Comment by mryab** [comment]
We've upgarded Bitsandbytes in https://github.com/learning-at-home/hivemind/pull/641, this should be fixed now
