### ISSUE TITLE
proto/runtime_pb2.py missing when installing from sources

### ISSUE THREAD

**Issue by poedator** [learning-at-home/hivemind#582]
After installing hivemind from sources, it fails to import with error:
`ImportError: cannot import name 'runtime_pb2' from 'hivemind.proto' (unknown location)`

tested on WSL and on Ubuntu
tested with latest master and with  1.1.9 release commit.
apparently proto/runtime_pb2.py is just not present in the sources. But where does it come from?

detailed error log:
```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hivemind as h
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rs/myhivemind/hivemind/__init__.py", line 1, in <module>
    from hivemind.averaging import DecentralizedAverager
  File "/home/rs/myhivemind/hivemind/averaging/__init__.py", line 1, in <module>
    from hivemind.averaging.averager import DecentralizedAverager
  File "/home/rs/myhivemind/hivemind/averaging/averager.py", line 20, in <module>
    from hivemind.averaging.allreduce import AllreduceException, AllReduceRunner, AveragingMode, GroupID
  File "/home/rs/myhivemind/hivemind/averaging/allreduce.py", line 7, in <module>
    from hivemind.averaging.partition import AllreduceException, BannedException, TensorPartContainer, TensorPartReducer
  File "/home/rs/myhivemind/hivemind/averaging/partition.py", line 11, in <module>
    from hivemind.compression import CompressionBase, CompressionInfo, NoCompression
  File "/home/rs/myhivemind/hivemind/compression/__init__.py", line 5, in <module>
    from hivemind.compression.adaptive import PerTensorCompression, RoleAdaptiveCompression, SizeAdaptiveCompression
  File "/home/rs/myhivemind/hivemind/compression/adaptive.py", line 6, in <module>
    from hivemind.compression.base import CompressionBase, CompressionInfo, Key, NoCompression, TensorRole
  File "/home/rs/myhivemind/hivemind/compression/base.py", line 11, in <module>
    from hivemind.proto import runtime_pb2
ImportError: cannot import name 'runtime_pb2' from 'hivemind.proto' (unknown location)
```

**Comment by poedator** [comment]
problem goes away if installing as described in https://learning-at-home.readthedocs.io/en/latest/user/quickstart.html#installation
specifically, adding `--no-use-pep517`
