### ISSUE TITLE
[BUG] Unable to start hivemind server when using gradient clipping 

### ISSUE THREAD

**Issue by SamAg19** [learning-at-home/hivemind#592]
**Describe the bug**
Trying to start up a hivemind server enabling gradient clipping `--clip_grad_norm` results in an error in https://github.com/learning-at-home/hivemind/blob/master/hivemind/moe/server/layers/optim.py due a setter property not being present for `defaults` in the file

**To Reproduce**
After starting up a dht peer, ran the following command:
Command:
`hivemind-server --expert_cls ffn --hidden_dim 512 --num_experts 5 --expert_pattern "expert.[0:5]" --initial_peers /ip4/172.29.152.117/tcp/45239/p2p/12D3KooWCAArT2ncW2H9BRoneEri4b2xh99SdMgXPZEuzkobx3bY --clip_grad_norm 1.0`

Output:
```
Sep 28 17:55:49.317 [INFO] Running DHT node on ['/ip4/172.29.152.117/tcp/38207/p2p/12D3KooWPEZEe796QZDZn8qCXXnC4RDxqkz6ADbAQ4fXLCeiMj5s', '/ip4/127.0.0.1/tcp/38207/p2p/12D3KooWPEZEe796QZDZn8qCXXnC4RDxqkz6ADbAQ4fXLCeiMj5s'], initial peers = ['/ip4/172.29.152.117/tcp/45239/p2p/12D3KooWCAArT2ncW2H9BRoneEri4b2xh99SdMgXPZEuzkobx3bY']
Sep 28 17:55:49.317 [INFO] Generating 5 expert uids from pattern expert.[0:5]
Traceback (most recent call last):
  File "/home/samag19/miniconda3/envs/py311/bin/hivemind-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/samag19/miniconda3/envs/py311/lib/python3.11/site-packages/hivemind/hivemind_cli/run_server.py", line 105, in main
    server = Server.create(**args, optim_cls=optim_cls, start=True, compression=compression)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samag19/miniconda3/envs/py311/lib/python3.11/site-packages/hivemind/moe/server/server.py", line 205, in create
    optimizer = ClippingWrapper(optimizer, clip_grad_norm)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samag19/miniconda3/envs/py311/lib/python3.11/site-packages/hivemind/moe/server/layers/optim.py", line 52, in __init__
    super().__init__(optim)
  File "/home/samag19/miniconda3/envs/py311/lib/python3.11/site-packages/hivemind/moe/server/layers/optim.py", line 8, in __init__
    super().__init__(optim.param_groups, optim.defaults)
  File "/home/samag19/miniconda3/envs/py311/lib/python3.11/site-packages/torch/optim/optimizer.py", line 171, in __init__
    self.defaults = defaults
    ^^^^^^^^^^^^^
AttributeError: property 'defaults' of 'ClippingWrapper' object has no setter
```

**Environment**
Please list:
* python version: 3.11.5
* hivemind.commit id: https://github.com/learning-at-home/hivemind/commit/28732521db96dd8e79e0a41e58979b163c7e6fc8
* Please copy and paste the output from pytorch [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
```
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.5
Libc version: glibc-2.35

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU
Nvidia driver version: 537.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 7735HS with Radeon Graphics
CPU family:                      25
Model:                           68
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        6387.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload umip vaes vpclmulqdq rdpid fsrm
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.1
[pip3] torch-optimizer==0.3.0
[pip3] triton==2.0.0
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

**Comment by mryab** [comment]
Hi @SamAg19, the pull request #593 should have fixed this issue. Could you please try installing from master and confirm that?

**Comment by SamAg19** [comment]
Its working now @mryab
